name: Update Nova Docs
on:
  workflow_dispatch:

jobs:
  latest-nova:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Config
        run: |
          git config --global user.name 't11s'
          git config --global user.email 'transmissionsdev@users.noreply.github.com'

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Update submodules
        run: git submodule update --remote --merge

      - name: Commit and push
        run: |
          git commit -am "Update Nova Docs"
          git push
