name: Update Nova Docs
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0/5 * * * *"

jobs:
  latest-nova:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Update submodules
        run: git submodule update --remote --merge

      - name: Commit and push
        run: |
          git commit -am "Update Nova Docs"
          git push
